### PR TITLE
Auto-generate supported board list from BSP metadata

### PR DESCRIPTION
**Pull request by utzig**
This updates the build system, to read BSP metadata including "name", "url", "description" and "arch", and auto-generate the list of supported boards in the landing page.

It requires that each BSP is updated with this metadata, and each new BSP has this metadata added to its "bsp.yml" file.

### CODE REVIEW

**Comment by utzig** [comment]
The reason for doing this PR is that "Supported Boards" on mynewt.apache.org is very outdated, and people will probably not want to maintain it up to date. For testing this change I added the following `bsp.yml` updates:

```diff
diff --git a/hw/bsp/nordic_pca10028/bsp.yml b/hw/bsp/nordic_pca10028/bsp.yml
index b2914f690..71e9bd22d 100644
--- a/hw/bsp/nordic_pca10028/bsp.yml
+++ b/hw/bsp/nordic_pca10028/bsp.yml
@@ -17,6 +17,9 @@
 # under the License.
 #
 
+bsp.name: "nRF51 DK"
+bsp.url: https://www.nordicsemi.com/eng/Products/Bluetooth-Smart-Bluetooth-low-energy/nRF51822
+bsp.description: "from Nordic Semiconductor"
 bsp.arch: cortex_m0
 bsp.compiler: compiler/arm-none-eabi-m0
 bsp.linkerscript:
diff --git a/hw/bsp/nordic_pca10056/bsp.yml b/hw/bsp/nordic_pca10056/bsp.yml
index dbeb98076..c373dbf96 100644
--- a/hw/bsp/nordic_pca10056/bsp.yml
+++ b/hw/bsp/nordic_pca10056/bsp.yml
@@ -17,6 +17,9 @@
 # under the License.
 #
 
+bsp.name: "nRF52840 Preview DK"
+bsp.url: https://www.nordicsemi.com/eng/Products/nRF52840-Preview-DK
+bsp.description: "from Nordic Semiconductor"
 bsp.arch: cortex_m4
 bsp.compiler: compiler/arm-none-eabi-m4
 bsp.linkerscript:
diff --git a/hw/bsp/nucleo-f767zi/bsp.yml b/hw/bsp/nucleo-f767zi/bsp.yml
index 771fbe9ed..c3c25bef8 100644
--- a/hw/bsp/nucleo-f767zi/bsp.yml
+++ b/hw/bsp/nucleo-f767zi/bsp.yml
@@ -17,6 +17,9 @@
 # under the License.
 #
 
+bsp.name: "NUCLEO-F767ZI"
+bsp.url: https://www.st.com/en/evaluation-tools/nucleo-f767zi.html
+bsp.description: "from ST Semiconductor"
 bsp.arch: cortex_m7
 bsp.compiler: compiler/arm-none-eabi-m7
 bsp.linkerscript:
diff --git a/hw/bsp/stm32f4discovery/bsp.yml b/hw/bsp/stm32f4discovery/bsp.yml
index ddda5ddca..e681f98c5 100644
--- a/hw/bsp/stm32f4discovery/bsp.yml
+++ b/hw/bsp/stm32f4discovery/bsp.yml
@@ -17,6 +17,9 @@
 # under the License.
 #
 
+bsp.name: "STM32F4DISCOVERY"
+bsp.url: https://www.st.com/en/evaluation-tools/stm32f4discovery.html
+bsp.description: "from ST Semiconductor"
 bsp.arch: cortex_m4
 bsp.compiler: compiler/arm-none-eabi-m4
 bsp.linkerscript:
```

This correctly generates the expected output on the landing page:

* nRF51 DK from Nordic Semiconductor (Cortex-M0)
* nRF52840 Preview DK from Nordic Semiconductor (Cortex-M4)
* NUCLEO-F767ZI from ST Semiconductor (Cortex-M7)
* STM32F4DISCOVERY from ST Semiconductor (Cortex-M4)

Of course every BSP needs to have its metadata updated for this to make sense! ;-)

/cc @aditihilbert @sterlinghughes @ccollins476ad

**Comment by utzig** [comment]
Any opinions?

**Comment by aditihilbert** [comment]
This is much needed - thanks!

**Comment by utzig** [comment]
Thanks, I will update `core` first, so it makes sense to merge this!

**Pull request merged**
